main: eu.auracraft.tntrun.Main
version: 2.2
name: TNTRun
api-version: 1.16
website: auracraft.eu
author: KM127PL
description: TNTRun Plugin made by KM127PL.
loadbefore: ["MULTIVERSE-CORE"]

commands:
  tnt:
    description: Main TNTRUN Command.
    usage: /<command> <tp, create, delete, recreate>
    permission: auracraft.tntrun