config-version: 1
plugin:
  prefix: "&8[&aTNTRun&8]&a"
  world:
    name: "tnt_run"
    size: 64
    blocks:
      pressure-plate: STONE_PRESSURE_PLATE
      gravity-blocks:
        - SAND
      tnt: TNT